server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Uzunmuddetli kes: hash-lenmis statik aktivler
    location /assets/ {
        try_files $uri =404;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    # SPA fallback — React Router route-lari index.html-e dusur
    location / {
        try_files $uri $uri/ /index.html;
    }
}
